service: hdfToSplunkViaS3
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  deploymentBucket:
    name: first-attempt-dev-sls-logs-bucket

functions:
  saf:
    handler: handler.saf

stepFunctions:
  stateMachines:
    hdfToSplunkViaS3Workflow:
      name: hdfToSplunkViaS3Workflow
      events:
        - cloudwatchEvent:
            event:
              source: 
                - aws.s3
              detail-type:
                - AWS API Call via CloudTrail
              detail:
                eventSource:
                  - s3.amazonaws.com
                eventName:
                  - PutObject
                requestParameters:
                  bucketName:
                    - sls-uploads-bucket
      definition:
        Comment: "Workflow initiated"
        StartAt: ValidatePass
        States:
          ValidatePass:
            Type: Pass
            Result: "Completed" # S3 contents
            Next: RunSaf
          RunSaf:
            Type: Task
            Resource:
              Fn::GetAtt: [saf, Arn]
            End: true

resources:
  Resources:
    slsCloudTrails3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: sls-uploads-bucket
    slsCloudTrails3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: first-attempt-dev-sls-logs-bucket
        PolicyDocument: 
          Statement:
            - Action:
                - 's3:GetBucketAcl'
              Effect: Allow
              Principal: '*'
              Resource:
                - arn:aws:s3:::first-attempt-dev-sls-logs-bucket
                - arn:aws:s3:::first-attempt-dev-sls-logs-bucket/*
            - Action:
                - 's3:PutObject'
              Effect: Allow
              Principal: '*'
              Resource:
                - arn:aws:s3:::first-attempt-dev-sls-logs-bucket
                - arn:aws:s3:::first-attempt-dev-sls-logs-bucket/*
    slsCloudTrail:
      DependsOn:
        - slsCloudTrails3BucketPolicy
      Type: AWS::CloudTrail::Trail
      Properties: 
        TrailName: sls-cloud-trail
        S3BucketName: first-attempt-dev-sls-logs-bucket
        IsLogging: true
        EventSelectors:
          - DataResources:
              - Type: AWS::S3::Object
                Values:
                  - arn:aws:s3:::sls-uploads-bucket/
            ReadWriteType: WriteOnly

plugins:
  - serverless-step-functions
  - serverless-deployment-bucket